from __future__ import annotations

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st


st.set_page_config(
    page_title="Bankruptcy Risk & Relative Grade",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

APP_DIR = Path(__file__).resolve().parent
ARTIFACT_PATH = APP_DIR / "rsf_grading_production_artifact.joblib"


st.markdown(
    """
    <style>
    .stApp {
        background:
            radial-gradient(circle at 8% 8%, rgba(37,99,235,0.08), transparent 24rem),
            radial-gradient(circle at 92% 15%, rgba(13,148,136,0.07), transparent 25rem),
            #f8fafc;
    }
    [data-testid="stSidebar"] {
        background: linear-gradient(180deg, #0f172a 0%, #111827 100%);
    }
    [data-testid="stSidebar"] * { color: #f8fafc; }
    .hero {
        padding: 1.6rem 1.8rem;
        border-radius: 22px;
        background: linear-gradient(120deg, #0f172a 0%, #1e3a8a 58%, #0f766e 125%);
        color: white;
        box-shadow: 0 16px 38px rgba(15,23,42,0.18);
        margin-bottom: 1.1rem;
    }
    .hero h1 { margin: 0; font-size: 2.05rem; letter-spacing: -0.035em; }
    .hero p { margin: .55rem 0 0 0; color: rgba(255,255,255,.84); }
    .grade-high {
        padding: 1rem 1.1rem; border-radius: 16px;
        background: #fff1f2; border: 1px solid #fecdd3;
        color: #9f1239; font-size: 1.13rem; font-weight: 700;
    }
    .grade-low {
        padding: 1rem 1.1rem; border-radius: 16px;
        background: #ecfdf5; border: 1px solid #a7f3d0;
        color: #065f46; font-size: 1.13rem; font-weight: 700;
    }
    .grade-event {
        padding: 1rem 1.1rem; border-radius: 16px;
        background: #fff7ed; border: 1px solid #fdba74;
        color: #9a3412; font-size: 1.13rem; font-weight: 700;
    }
    .note {
        padding: .9rem 1rem; border-radius: 12px;
        background: #f1f5f9; color: #475569;
        border-left: 4px solid #64748b;
    }
    </style>
    """,
    unsafe_allow_html=True,
)


@st.cache_resource(show_spinner="Loading locked RSF grading model…")
def load_artifact():
    if not ARTIFACT_PATH.exists():
        raise FileNotFoundError(
            "rsf_grading_production_artifact.joblib is missing. "
            "Deploy the complete Streamlit ZIP generated by the analysis pipeline."
        )
    return joblib.load(ARTIFACT_PATH)


artifact = load_artifact()

FEATURES = list(artifact["features"])
model = artifact["model"]
imputer = artifact["imputer"]
clip_low = np.asarray(artifact["clip_low"], dtype=float)
clip_high = np.asarray(artifact["clip_high"], dtype=float)
q01 = np.asarray(artifact["feature_q01"], dtype=float)
q99 = np.asarray(artifact["feature_q99"], dtype=float)
threshold_36m = float(artifact["production_threshold_36m"])
support = artifact["horizon_support"]

FEATURE_HELP = {
    "Working Capital / Total Assets": "Decimal ratio.",
    "Cash + Short-Term Investments / Assets": "Decimal ratio.",
    "Total Debt / Assets": "Decimal ratio.",
    "Total Liabilities / Assets": "Decimal ratio.",
    "Short-Term Debt / Assets": "Decimal ratio.",
    "ROA": "Return on assets in decimal form; e.g. 0.085 = 8.5%.",
    "Retained Earnings / Assets": "Decimal ratio.",
    "Operating Cash Flow / Current Liabilities": "Decimal ratio.",
    "Free Cash Flow / Total Assets": "Decimal ratio.",
    "Asset Turnover": "Revenue / total assets.",
    "R&D / Assets": "Decimal ratio.",
    "Capex / Assets": "Decimal ratio.",
    "SG&A / Assets": "Decimal ratio.",
    "Accounts Payable / Assets": "Decimal ratio.",
    "Current Liabilities / Assets": "Decimal ratio.",
    "Accruals / Assets": "Decimal ratio.",
    "ln(Total Assets)": "Natural logarithm of total assets — do not enter raw total assets.",
    "Current Ratio": "Current assets / current liabilities.",
}


st.markdown(
    """
    <div class="hero">
        <h1>Bankruptcy Risk & Relative Grading System</h1>
        <p>
            Locked Random Survival Forest · 18 engineered financial predictors ·
            cumulative bankruptcy risk through 36 months
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)

st.info(
    "This interface expects the same 18 engineered predictors used during model development. "
    "Blank fields are permitted and are explicitly median-imputed by the locked production preprocessing."
)

with st.sidebar:
    st.markdown("## Grading rule")
    st.metric(
        "36-month relative High-Risk cutoff",
        f"{100.0*threshold_36m:.2f}%",
    )
    st.caption(
        "Relative High Risk = predicted 36-month risk at or above the "
        "development-cohort median on the final production model's risk scale."
    )
    st.markdown("---")
    st.markdown("### Supported display horizons")
    st.caption(
        f"18m: {support['18m_events']} development events · "
        f"24m: {support['24m_events']} · "
        f"36m: {support['36m_events']}"
    )
    st.caption(
        "12-month risk is not highlighted because the development data had only "
        f"{support['12m_events']} bankruptcy event by 12 months."
    )
    st.markdown("---")
    already_bankrupt = st.checkbox(
        "Bankruptcy has already occurred",
        value=False,
        help=(
            "Observed outcome only; never used as a model predictor. "
            "Once bankruptcy has occurred, prospective High/Low grading is secondary."
        ),
    )


def parse_numeric(text: str):
    text = text.strip()
    if text == "":
        return np.nan
    return float(text)


with st.form("company_features"):
    st.subheader("Company financial profile")
    st.caption(
        "Leave a field blank only when genuinely unavailable. "
        "Do not enter percentages as whole numbers unless the development variable used that scale."
    )

    values_text = {}

    tabs = st.tabs(
        [
            "Liquidity & leverage",
            "Profitability & cash flow",
            "Operating structure",
        ]
    )

    groups = [
        FEATURES[:6],
        FEATURES[6:12],
        FEATURES[12:],
    ]

    feature_index = {
        feature: index
        for index, feature in enumerate(FEATURES)
    }

    for tab, group in zip(tabs, groups):
        with tab:
            cols = st.columns(2)
            for position, feature in enumerate(group):
                i = feature_index[feature]
                with cols[position % 2]:
                    values_text[feature] = st.text_input(
                        feature,
                        value="",
                        placeholder="Enter value or leave blank",
                        help=(
                            f"{FEATURE_HELP.get(feature, '')} "
                            f"Development 1st–99th percentile: {q01[i]:.4g} to {q99[i]:.4g}."
                        ),
                        key=f"input_{i}",
                    )

    submitted = st.form_submit_button(
        "Generate risk trajectory and grade",
        type="primary",
        use_container_width=True,
    )


def transform_input(raw_vector):
    clipped = np.clip(raw_vector, clip_low, clip_high)
    transformed = imputer.transform(clipped.reshape(1, -1))
    return transformed, clipped


def evaluate_survival_function(fn, times):
    result = []
    first = float(fn.x[0])
    last = float(fn.x[-1])

    for t in times:
        if t < first:
            value = 1.0
        elif t > last:
            value = float(fn(last))
        else:
            value = float(fn(float(t)))
        result.append(value)

    return np.asarray(result, dtype=float)


def risk_at_day(times, risk, day):
    idx = np.searchsorted(times, day, side="right") - 1
    idx = max(0, min(idx, len(risk) - 1))
    return float(risk[idx])


if submitted:
    parsed = []
    invalid = []

    for feature in FEATURES:
        try:
            parsed.append(parse_numeric(values_text[feature]))
        except ValueError:
            invalid.append(feature)
            parsed.append(np.nan)

    if invalid:
        st.error(
            "These fields are not valid numbers: "
            + ", ".join(invalid)
        )
        st.stop()

    raw_vector = np.asarray(parsed, dtype=float)

    missing_features = [
        FEATURES[i]
        for i in range(len(FEATURES))
        if not np.isfinite(raw_vector[i])
    ]

    transformed, clipped = transform_input(raw_vector)

    clipped_features = [
        FEATURES[i]
        for i in range(len(FEATURES))
        if np.isfinite(raw_vector[i])
        and not np.isclose(raw_vector[i], clipped[i])
    ]

    fn = model.predict_survival_function(transformed)[0]
    model_times = np.asarray(fn.x, dtype=float)

    times = np.unique(
        np.concatenate(
            [
                np.array([0.0, 548.0, 730.0, 1094.0]),
                model_times[
                    (model_times > 0)
                    & (model_times <= 1094.0)
                ],
            ]
        )
    )

    survival = evaluate_survival_function(fn, times)
    risk = np.clip(1.0 - survival, 0.0, 1.0)

    risk_18 = risk_at_day(times, risk, 548.0)
    risk_24 = risk_at_day(times, risk, 730.0)
    risk_36 = risk_at_day(times, risk, 1094.0)

    model_grade = (
        "Relative High Risk"
        if risk_36 >= threshold_36m
        else "Relative Low Risk"
    )

    metric_cols = st.columns(3)
    metric_cols[0].metric("18-month risk", f"{100*risk_18:.2f}%")
    metric_cols[1].metric("24-month risk", f"{100*risk_24:.2f}%")
    metric_cols[2].metric("36-month risk", f"{100*risk_36:.2f}%")

    st.markdown("### Grading result")

    if already_bankrupt:
        st.markdown(
            """
            <div class="grade-event">
            BANKRUPTCY ALREADY OBSERVED — observed event supersedes prospective grading
            </div>
            """,
            unsafe_allow_html=True,
        )
        st.caption(
            f"Model-based grade from the supplied baseline profile: {model_grade}."
        )

    elif model_grade == "Relative High Risk":
        st.markdown(
            f"""
            <div class="grade-high">
            RELATIVE HIGH RISK · 36-month predicted risk {100*risk_36:.2f}% ≥
            cutoff {100*threshold_36m:.2f}%
            </div>
            """,
            unsafe_allow_html=True,
        )

    else:
        st.markdown(
            f"""
            <div class="grade-low">
            RELATIVE LOW RISK · 36-month predicted risk {100*risk_36:.2f}% &lt;
            cutoff {100*threshold_36m:.2f}%
            </div>
            """,
            unsafe_allow_html=True,
        )

    margin_pp = 100.0 * (risk_36 - threshold_36m)
    st.caption(
        f"Distance from grading cutoff: {margin_pp:+.2f} percentage points. "
        "This is a risk-margin, not a calibrated confidence score."
    )

    plot_df = pd.DataFrame(
        {
            "Months": times / 30.4375,
            "RiskPercent": 100.0 * risk,
        }
    )

    fig = go.Figure()

    fig.add_trace(
        go.Scatter(
            x=plot_df["Months"],
            y=plot_df["RiskPercent"],
            mode="lines",
            line={"width": 4, "shape": "hv"},
            name="Cumulative bankruptcy risk",
            hovertemplate=(
                "<b>%{x:.1f} months</b><br>"
                "Predicted risk: %{y:.2f}%"
                "<extra></extra>"
            ),
        )
    )

    fig.add_trace(
        go.Scatter(
            x=[18, 24, 36],
            y=[100*risk_18, 100*risk_24, 100*risk_36],
            mode="markers+text",
            text=[
                f"18m · {100*risk_18:.2f}%",
                f"24m · {100*risk_24:.2f}%",
                f"36m · {100*risk_36:.2f}%",
            ],
            textposition="top center",
            showlegend=False,
            hovertemplate="%{text}<extra></extra>",
        )
    )

    fig.add_trace(
        go.Scatter(
            x=[36],
            y=[100.0*threshold_36m],
            mode="markers+text",
            marker={"symbol": "diamond-open", "size": 13},
            text=[f"36m cutoff · {100*threshold_36m:.2f}%"],
            textposition="bottom center",
            showlegend=False,
            hovertemplate="%{text}<extra></extra>",
        )
    )

    fig.update_layout(
        height=520,
        margin={"l": 30, "r": 20, "t": 45, "b": 30},
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(255,255,255,0.88)",
        xaxis={
            "title": "Months from baseline",
            "range": [0, 36],
            "tickvals": [0, 6, 12, 18, 24, 30, 36],
        },
        yaxis={
            "title": "Cumulative model-predicted bankruptcy risk (%)",
            "rangemode": "tozero",
            "ticksuffix": "%",
        },
        showlegend=False,
    )

    st.plotly_chart(
        fig,
        use_container_width=True,
        config={"displaylogo": False},
    )

    if missing_features:
        st.warning(
            f"{len(missing_features)} of 18 predictors were missing and were "
            "median-imputed by the locked production preprocessing."
        )
        with st.expander("Imputed predictors"):
            st.write(", ".join(missing_features))

    if clipped_features:
        st.warning(
            f"{len(clipped_features)} entered value(s) were outside the locked "
            "0.5th–99.5th percentile preprocessing bounds and were clipped."
        )
        with st.expander("Clipped predictors"):
            st.write(", ".join(clipped_features))

    export = {
        feature: (
            None
            if not np.isfinite(raw_vector[i])
            else float(raw_vector[i])
        )
        for i, feature in enumerate(FEATURES)
    }

    export.update(
        {
            "Predicted_Risk_18m": risk_18,
            "Predicted_Risk_24m": risk_24,
            "Predicted_Risk_36m": risk_36,
            "Production_Threshold_36m": threshold_36m,
            "Relative_Grade": model_grade,
            "Risk_Margin_Percentage_Points": margin_pp,
            "Missing_Predictor_Count": len(missing_features),
            "Observed_Already_Bankrupt": bool(already_bankrupt),
        }
    )

    st.download_button(
        "Download prediction",
        data=pd.DataFrame([export]).to_csv(index=False).encode("utf-8"),
        file_name="bankruptcy_risk_and_relative_grade.csv",
        mime="text/csv",
        use_container_width=True,
    )

    st.markdown(
        """
        <div class="note">
        <b>Interpretation:</b> “Relative High Risk” means above the locked
        development-cohort median on the final model's 36-month predicted-risk
        scale. It does not mean bankruptcy is certain or that the probability is
        an externally calibrated absolute probability. “Relative Low Risk” does
        not mean zero risk.
        </div>
        """,
        unsafe_allow_html=True,
    )

else:
    st.info("Enter the 18 engineered predictors, then submit the form.")

with st.expander("Methodology and deployment notes"):
    st.write(
        "The app uses the final full-development Random Survival Forest and the "
        "same training-derived median-risk cutoff procedure evaluated during "
        "internal cross-validation."
    )
    st.write(
        "The validation p-value was never used to select or move the cutoff. "
        "The app expects the already-engineered 18 predictors; it does not infer "
        "them from raw accounting statements."
    )
